######################## default configuration ####################
baseURL = "/"
title = "Die Mobiliar - Engineering Blog"
theme = "bookworm-light"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Image Processing ##############################
[imaging]
quality = "95"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "/style.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "42px"
h1_lg = "38px"
h1_md = "30px"

h2 = "38px"
h2_md = "30px"

h3 = "30px"
h3_md = "24px"

h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#007b91"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#70c3d4"

#################### default parameters ################################
[params]
logo = "images/logo.svg"
logo_width = "110px"
favicon = "images/favicon.png"
# Meta data
description = "Engineering Blog of Swiss Insurance Company Die Mobiliar"
author = "Die Mobiliar"
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "© Die Mobiliar 2023"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

############################# Footer Menu ########################
[[menu.footer]]
name = "Mobiliar Website"
url = "https://www.mobiliar.ch/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "contact/"
weight = 3

# [[menu.footer]]
# name = "Terms & Conditions"
# url = "terms-conditions/"
# weight = 4

# Social Icons
[[params.social]]
icon = "lab la-facebook-f"
url = "https://www.facebook.com/diemobiliar"

[[params.social]]
icon = "lab la-twitter"
url = "https://twitter.com/diemobiliar"

[[params.social]]
icon = "lab la-instagram"
url = "https://www.instagram.com/diemobiliar/"

[[params.social]]
icon = "lab la-linkedin-in"
url = "https://www.linkedin.com/company/die-mobiliar"

[[params.social]]
icon = "lab la-github"
url = "https://github.com/diemobiliar/"
